spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost\MSSQLSERVER:1433;database=batch_meta_data;encrypt=false;trustServerCertificate=true;hostNameInCertificate=any;trustStore=any;trustStorePassword=any;
    username: sa
    password: root
  batch:
    jdbc:
      initialize-schema: always
logging:
  level:
    org.springframework.jdbc: DEBUG

table:
  prefix: BATCH_
